server:
  port: 19509

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/

spring:
  application:
    name: coupon-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: coupon-service
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://localhost:5435/coupon_db
    driver-class-name: org.postgresql.Driver
    username: coupon_user
    password: coupon_pass

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6378
      password:

  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 보안 관련(BCrypt)
security:
  bcrypt:
    cost: 10

# Swagger
springdoc:
  api-docs:
    path: /api-docs        # 기본은 /v3/api-docs, 커스텀 사용 시 여기로 노출
  swagger-ui:
    path: /                 # 기본은 /swagger-ui/index.html, 여기로 접속 가능
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none

# 공통 로깅(상세 SQL 로깅은 프로파일에서 분리)
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info

coupon:
  reservation:
    expiration:
      fixed-delay-ms: 60000
      batch-size: 100
