server:
  port: 19509

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9090/eureka/

spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://localhost:5433/rocket_delivery_db
    driver-class-name: org.postgresql.Driver
    username: app_user
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# ?? ??(BCrypt)
security:
  bcrypt:
    cost: 10

# Swagger
springdoc:
  api-docs:
    path: /api-docs        # ??? /v3/api-docs, ??? ?? ? ??? ??
  swagger-ui:
    path: /                 # ??? /swagger-ui/index.html, ??? ?? ??
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none

# ?? ??(?? SQL ??? ?????? ??)
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info
