server:
  port: 19504

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/

spring:
  application:
    name: hub-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hub-service

  datasource:
    url: jdbc:postgresql://localhost:5433/rocket_delivery_db
    driver-class-name: org.postgresql.Driver
    username: app_user
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 보안 관련(BCrypt)
security:
  bcrypt:
    cost: 10

# Swagger
springdoc:
  api-docs:
    path: /api-docs        # 기본은 /v3/api-docs, 커스텀 사용 시 여기로 노출
  swagger-ui:
    path: /                 # 기본은 /swagger-ui/index.html, 여기로 접속 가능
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none

# 공통 로깅(상세 SQL 로깅은 프로파일에서 분리)
logging:
  level:
    org.sparta.common.event: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info

app:
  eventpublisher:
    enabled: true