server:
  port: 19506

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5434/product_db
    driver-class-name: org.postgresql.Driver
    username: product_user
    password: product_pass

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Kafka 설정 (임시 - 추후 module-kafka로 분리 예정)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-service

# 보안 관련(BCrypt)
security:
  bcrypt:
    cost: 10

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none

# 공통 로깅(상세 SQL 로깅은 프로파일에서 분리)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: DEBUG

# zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"