server:
  port: 19500

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/

rate-limit:
  replenish-rate: 5
  burst-capacity: 10
  requested-tokens: 1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: common-service
          uri: lb://COMMON-SERVICE
          predicates:
            - Path=/common/**, /commons/**
        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/admin/companies/**, /companies/**
          filters:
            - RewritePath=/companies/(?<segment>.*), /api/companies/${segment}
            - RewritePath=/admin/companies/(?<segment>.*), /api/admin/companies/${segment}
        - id: delivery-log-service
          uri: lb://DELIVERY-LOG-SERVICE
          predicates:
            - Path=/delivery-logs/**, /delivery-log/**
          filters:
            - RewritePath=/delivery-logs/(?<segment>.*), /$\{segment}
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/deliveries/**
          filters:
            - RewritePath=/deliveries/(?<segment>.*), /api/deliveries/${segment}
        - id: hub-service
          uri: lb://HUB-SERVICE
          predicates:
            - Path=/hubs/**, /admin/hubs/**, /hub-routes/**
          filters:
            - RewritePath=/hubs/(?<segment>.*), /api/hubs/${segment}
            - RewritePath=/admin/hubs/(?<segment>.*), /api/admin/hubs/${segment}
            - RewritePath=/hub-routes/(?<segment>.*), /api/hub-routes/${segment}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /api/orders/${segment}
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products/(?<segment>.*), /api/products/${segment}
        - id: slack-service
          uri: lb://SLACK-SERVICE
          predicates:
            - Path=/slack/**, /slacks/**
          filters:
            - RewritePath=/slack/(?<segment>.*), /api/slack/${segment}
            - RewritePath=/slacks/(?<segment>.*), /api/slacks/${segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /api/users/${segment}
        - id: auth-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /api/auth/${segment}
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
                redis-rate-limiter.requestedTokens: 1
        - id: jpa-service
          uri: lb://JPA-SERVICE
          predicates:
            - Path=/jpa/**
  data:
    redis:
      host: localhost
      port: 6378


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Product Service
        url: /product/api-docs
      - name: User Service
        url: /user/api-docs
      - name: Order Service
        url: /order/api-docs
      - name: Hub Service
        url: /hub/api-docs
      - name: Company Service
        url: /company/api-docs
      - name: Delivery Log Service
        url: /delivery-logs/api-docs
      - name: Delivery Service
        url: /delivery/api-docs
      - name: Slack Service
        url: /slack/api-docs
      - name: DeliveryLog Service
        url: /deliveryLog/api-docs
      - name: DelvieryMan Service
        url: /deliveryMan/api-docs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG
    org.springframework.data.redis: DEBUG