server:
  port: 19500

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: common-service
          uri: lb://COMMON-SERVICE
          predicates:
            - Path=/common/**, /commons/**
        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/company/**, /companies/**
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery/**, /deliveries/**
        - id: hub-service
          uri: lb://HUB-SERVICE
          predicates:
            - Path=/hub/**, /hubs/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**, /orders/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**, /products/**
        - id: slack-service
          uri: lb://SLACK-SERVICE
          predicates:
            - Path=/slack/**, /slacks/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**, /users/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG